### ISSUE TITLE
cannot reload datapacks on neoforge or older forge versions

### ISSUE THREAD

**Issue by xg787** [NotSoEpic/deepdrilling#13]
[latest - neoforge 47.1.106.log](https://github.com/user-attachments/files/17082548/latest.-.neoforge.47.1.106.log)
[latest - forge 47.2.17.log](https://github.com/user-attachments/files/17082549/latest.-.forge.47.2.17.log)

**Comment by DrowningFish233** [comment]
I'm experiencing the same issue as well.
