### ISSUE TITLE
[Feature Request] locate Command

### ISSUE THREAD

**Issue by Autumli** [NotSoEpic/deepdrilling#16]
Hi, love the mod.
I'm finding it hard to troubleshoot and test without a /locate command for the ore nodes. I don't know if this is possible to implement, but if it is it would be really helpful.

**Comment by mkern1200** [comment]
There's a locate command for the nodes in the latest version of the mod.  Just use "/locate structure deepdrilling:<node type>".  It'll take you to the surface of the world above the node.

**Comment by NotSoEpic** [comment]
You might need to look around a little bit too, the /locate coordinates are consistently offset by a chunk or two diagonally at the moment
