### ISSUE TITLE
Copper and Brass Drill recipe doesn't show up in REI

### ISSUE THREAD

**Issue by JJRobot25** [NotSoEpic/deepdrilling#4]
As the title says. With JEI they show up just fine, along the other sequenced assembly recipes, but when using REI they're nowhere to be seen...

**Comment by NotSoEpic** [comment]
Could you provide more information?
It works fine for me using just Deep Drilling + REI (and dependencies)
![image](https://github.com/user-attachments/assets/54abf2f8-4937-4b09-8c15-3b061f836f8f)

**Comment by JJRobot25** [comment]
I've made a fresh instance (forge 1.20.1 - 47.2.17) with just the latest versions of Create, Deep Drilling, REI, Architectury and Cloth Config.
The recipe still doesn't show up in REI. I can still craft it though with the sequenced assembly

**Comment by NotSoEpic** [comment]
Oh - I was checking with just Fabric
Create for Forge doesn't have REI support, so no recipes from any of its custom recipe types will show up

Try [REI Plugin Compatibility](https://modrinth.com/mod/roughly-enough-items-hacks), it's advertised as "extremely unstable, invokes terrible hacks, and should be used as a last resort", but seemingly works just fine

**Comment by JJRobot25** [comment]
I  had that installed in my pack, but adding it to my fresh instance seems to fix it. I also updated to the latest version of Deep Drilling, maybe that has something to do with it. Thanks!
