### ISSUE TITLE
[Feature Request] Parity/Compat with Create: Enchantable Machinery

### ISSUE THREAD

**Issue by Royal-Jelly** [NotSoEpic/deepdrilling#7]
[Create: Enchantable Machinery](https://modrinth.com/mod/create-enchantable-machinery) allows base create "Mechanical Drills" to be enchanted. Imagine an unbreaking IV, Fortune IV Drill head, could be a cool feature.

**Comment by NotSoEpic** [comment]
Implemented with c9b2ca2e520148cc2da7a66261bc3842ea4601a8, it'll be in the next version :tada:
Now tack on efficiency VI to the enchantment shopping list :3 ~~... when i fix the 0.5s quantization of drilling speed~~
